// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: movie_match.proto

package com.moviematch;

public final class MovieMatchProtos {
  private MovieMatchProtos() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }
  public interface MovieOpinionOrBuilder extends
      // @@protoc_insertion_point(interface_extends:MovieOpinion)
      com.google.protobuf.MessageLiteOrBuilder {

    /**
     * <code>uint64 user_id = 1;</code>
     */
    long getUserId();

    /**
     * <code>string movie_name = 2;</code>
     */
    java.lang.String getMovieName();
    /**
     * <code>string movie_name = 2;</code>
     */
    com.google.protobuf.ByteString
        getMovieNameBytes();

    /**
     * <code>bool thumbs_up = 3;</code>
     */
    boolean getThumbsUp();
  }
  /**
   * <pre>
   * [START messages]
   * </pre>
   *
   * Protobuf type {@code MovieOpinion}
   */
  public  static final class MovieOpinion extends
      com.google.protobuf.GeneratedMessageLite<
          MovieOpinion, MovieOpinion.Builder> implements
      // @@protoc_insertion_point(message_implements:MovieOpinion)
      MovieOpinionOrBuilder {
    private MovieOpinion() {
      movieName_ = "";
    }
    public static final int USER_ID_FIELD_NUMBER = 1;
    private long userId_;
    /**
     * <code>uint64 user_id = 1;</code>
     */
    @java.lang.Override
    public long getUserId() {
      return userId_;
    }
    /**
     * <code>uint64 user_id = 1;</code>
     */
    private void setUserId(long value) {
      
      userId_ = value;
    }
    /**
     * <code>uint64 user_id = 1;</code>
     */
    private void clearUserId() {
      
      userId_ = 0L;
    }

    public static final int MOVIE_NAME_FIELD_NUMBER = 2;
    private java.lang.String movieName_;
    /**
     * <code>string movie_name = 2;</code>
     */
    @java.lang.Override
    public java.lang.String getMovieName() {
      return movieName_;
    }
    /**
     * <code>string movie_name = 2;</code>
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getMovieNameBytes() {
      return com.google.protobuf.ByteString.copyFromUtf8(movieName_);
    }
    /**
     * <code>string movie_name = 2;</code>
     */
    private void setMovieName(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      movieName_ = value;
    }
    /**
     * <code>string movie_name = 2;</code>
     */
    private void clearMovieName() {
      
      movieName_ = getDefaultInstance().getMovieName();
    }
    /**
     * <code>string movie_name = 2;</code>
     */
    private void setMovieNameBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      movieName_ = value.toStringUtf8();
    }

    public static final int THUMBS_UP_FIELD_NUMBER = 3;
    private boolean thumbsUp_;
    /**
     * <code>bool thumbs_up = 3;</code>
     */
    @java.lang.Override
    public boolean getThumbsUp() {
      return thumbsUp_;
    }
    /**
     * <code>bool thumbs_up = 3;</code>
     */
    private void setThumbsUp(boolean value) {
      
      thumbsUp_ = value;
    }
    /**
     * <code>bool thumbs_up = 3;</code>
     */
    private void clearThumbsUp() {
      
      thumbsUp_ = false;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (userId_ != 0L) {
        output.writeUInt64(1, userId_);
      }
      if (!movieName_.isEmpty()) {
        output.writeString(2, getMovieName());
      }
      if (thumbsUp_ != false) {
        output.writeBool(3, thumbsUp_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (userId_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt64Size(1, userId_);
      }
      if (!movieName_.isEmpty()) {
        size += com.google.protobuf.CodedOutputStream
          .computeStringSize(2, getMovieName());
      }
      if (thumbsUp_ != false) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(3, thumbsUp_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    public static com.moviematch.MovieMatchProtos.MovieOpinion parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static com.moviematch.MovieMatchProtos.MovieOpinion parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static com.moviematch.MovieMatchProtos.MovieOpinion parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static com.moviematch.MovieMatchProtos.MovieOpinion parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static com.moviematch.MovieMatchProtos.MovieOpinion parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static com.moviematch.MovieMatchProtos.MovieOpinion parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static com.moviematch.MovieMatchProtos.MovieOpinion parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static com.moviematch.MovieMatchProtos.MovieOpinion parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static com.moviematch.MovieMatchProtos.MovieOpinion parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input);
    }
    public static com.moviematch.MovieMatchProtos.MovieOpinion parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static com.moviematch.MovieMatchProtos.MovieOpinion parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static com.moviematch.MovieMatchProtos.MovieOpinion parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }

    public static Builder newBuilder() {
      return (Builder) DEFAULT_INSTANCE.createBuilder();
    }
    public static Builder newBuilder(com.moviematch.MovieMatchProtos.MovieOpinion prototype) {
      return (Builder) DEFAULT_INSTANCE.createBuilder(prototype);
    }

    /**
     * <pre>
     * [START messages]
     * </pre>
     *
     * Protobuf type {@code MovieOpinion}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageLite.Builder<
          com.moviematch.MovieMatchProtos.MovieOpinion, Builder> implements
        // @@protoc_insertion_point(builder_implements:MovieOpinion)
        com.moviematch.MovieMatchProtos.MovieOpinionOrBuilder {
      // Construct using com.moviematch.MovieMatchProtos.MovieOpinion.newBuilder()
      private Builder() {
        super(DEFAULT_INSTANCE);
      }


      /**
       * <code>uint64 user_id = 1;</code>
       */
      @java.lang.Override
      public long getUserId() {
        return instance.getUserId();
      }
      /**
       * <code>uint64 user_id = 1;</code>
       */
      public Builder setUserId(long value) {
        copyOnWrite();
        instance.setUserId(value);
        return this;
      }
      /**
       * <code>uint64 user_id = 1;</code>
       */
      public Builder clearUserId() {
        copyOnWrite();
        instance.clearUserId();
        return this;
      }

      /**
       * <code>string movie_name = 2;</code>
       */
      @java.lang.Override
      public java.lang.String getMovieName() {
        return instance.getMovieName();
      }
      /**
       * <code>string movie_name = 2;</code>
       */
      @java.lang.Override
      public com.google.protobuf.ByteString
          getMovieNameBytes() {
        return instance.getMovieNameBytes();
      }
      /**
       * <code>string movie_name = 2;</code>
       */
      public Builder setMovieName(
          java.lang.String value) {
        copyOnWrite();
        instance.setMovieName(value);
        return this;
      }
      /**
       * <code>string movie_name = 2;</code>
       */
      public Builder clearMovieName() {
        copyOnWrite();
        instance.clearMovieName();
        return this;
      }
      /**
       * <code>string movie_name = 2;</code>
       */
      public Builder setMovieNameBytes(
          com.google.protobuf.ByteString value) {
        copyOnWrite();
        instance.setMovieNameBytes(value);
        return this;
      }

      /**
       * <code>bool thumbs_up = 3;</code>
       */
      @java.lang.Override
      public boolean getThumbsUp() {
        return instance.getThumbsUp();
      }
      /**
       * <code>bool thumbs_up = 3;</code>
       */
      public Builder setThumbsUp(boolean value) {
        copyOnWrite();
        instance.setThumbsUp(value);
        return this;
      }
      /**
       * <code>bool thumbs_up = 3;</code>
       */
      public Builder clearThumbsUp() {
        copyOnWrite();
        instance.clearThumbsUp();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:MovieOpinion)
    }
    @java.lang.Override
    @java.lang.SuppressWarnings({"unchecked", "fallthrough"})
    protected final java.lang.Object dynamicMethod(
        com.google.protobuf.GeneratedMessageLite.MethodToInvoke method,
        java.lang.Object arg0, java.lang.Object arg1) {
      switch (method) {
        case NEW_MUTABLE_INSTANCE: {
          return new com.moviematch.MovieMatchProtos.MovieOpinion();
        }
        case NEW_BUILDER: {
          return new Builder();
        }
        case IS_INITIALIZED: {
          return DEFAULT_INSTANCE;
        }
        case MAKE_IMMUTABLE: {
          return null;
        }
        case VISIT: {
          Visitor visitor = (Visitor) arg0;
          com.moviematch.MovieMatchProtos.MovieOpinion other = (com.moviematch.MovieMatchProtos.MovieOpinion) arg1;
          userId_ = visitor.visitLong(userId_ != 0L, userId_,
              other.userId_ != 0L, other.userId_);
          movieName_ = visitor.visitString(!movieName_.isEmpty(), movieName_,
              !other.movieName_.isEmpty(), other.movieName_);
          thumbsUp_ = visitor.visitBoolean(thumbsUp_ != false, thumbsUp_,
              other.thumbsUp_ != false, other.thumbsUp_);
          if (visitor == com.google.protobuf.GeneratedMessageLite.MergeFromVisitor
              .INSTANCE) {
          }
          return this;
        }
        case MERGE_FROM_STREAM: {
          com.google.protobuf.CodedInputStream input =
              (com.google.protobuf.CodedInputStream) arg0;
          com.google.protobuf.ExtensionRegistryLite extensionRegistry =
              (com.google.protobuf.ExtensionRegistryLite) arg1;
          if (extensionRegistry == null) {
            throw new java.lang.NullPointerException();
          }
          try {
            boolean done = false;
            while (!done) {
              int tag = input.readTag();
              switch (tag) {
                case 0:
                  done = true;
                  break;
                case 8: {

                  userId_ = input.readUInt64();
                  break;
                }
                case 18: {
                  java.lang.String s = input.readStringRequireUtf8();

                  movieName_ = s;
                  break;
                }
                case 24: {

                  thumbsUp_ = input.readBool();
                  break;
                }
                default: {
                  if (!parseUnknownField(tag, input)) {
                    done = true;
                  }
                  break;
                }
              }
            }
          } catch (com.google.protobuf.InvalidProtocolBufferException e) {
            throw new RuntimeException(e.setUnfinishedMessage(this));
          } catch (java.io.IOException e) {
            throw new RuntimeException(
                new com.google.protobuf.InvalidProtocolBufferException(
                    e.getMessage()).setUnfinishedMessage(this));
          } finally {
          }
        }
        // fall through
        case GET_DEFAULT_INSTANCE: {
          return DEFAULT_INSTANCE;
        }
        case GET_PARSER: {
          com.google.protobuf.Parser<com.moviematch.MovieMatchProtos.MovieOpinion> parser = PARSER;
          if (parser == null) {
            synchronized (com.moviematch.MovieMatchProtos.MovieOpinion.class) {
              parser = PARSER;
              if (parser == null) {
                parser = new DefaultInstanceBasedParser(DEFAULT_INSTANCE);
                PARSER = parser;
              }
            }
          }
          return parser;
      }
      case GET_MEMOIZED_IS_INITIALIZED: {
        return (byte) 1;
      }
      case SET_MEMOIZED_IS_INITIALIZED: {
        return null;
      }
      }
      throw new UnsupportedOperationException();
    }


    // @@protoc_insertion_point(class_scope:MovieOpinion)
    private static final com.moviematch.MovieMatchProtos.MovieOpinion DEFAULT_INSTANCE;
    static {
      // New instances are implicitly immutable so no need to make
      // immutable.
      DEFAULT_INSTANCE = new MovieOpinion();
    }

    public static com.moviematch.MovieMatchProtos.MovieOpinion getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static volatile com.google.protobuf.Parser<MovieOpinion> PARSER;

    public static com.google.protobuf.Parser<MovieOpinion> parser() {
      return DEFAULT_INSTANCE.getParserForType();
    }
  }

  public interface MovieListOrBuilder extends
      // @@protoc_insertion_point(interface_extends:MovieList)
      com.google.protobuf.MessageLiteOrBuilder {

    /**
     * <code>repeated string movie_names = 1;</code>
     */
    java.util.List<java.lang.String>
        getMovieNamesList();
    /**
     * <code>repeated string movie_names = 1;</code>
     */
    int getMovieNamesCount();
    /**
     * <code>repeated string movie_names = 1;</code>
     */
    java.lang.String getMovieNames(int index);
    /**
     * <code>repeated string movie_names = 1;</code>
     */
    com.google.protobuf.ByteString
        getMovieNamesBytes(int index);
  }
  /**
   * Protobuf type {@code MovieList}
   */
  public  static final class MovieList extends
      com.google.protobuf.GeneratedMessageLite<
          MovieList, MovieList.Builder> implements
      // @@protoc_insertion_point(message_implements:MovieList)
      MovieListOrBuilder {
    private MovieList() {
      movieNames_ = com.google.protobuf.GeneratedMessageLite.emptyProtobufList();
    }
    public static final int MOVIE_NAMES_FIELD_NUMBER = 1;
    private com.google.protobuf.Internal.ProtobufList<java.lang.String> movieNames_;
    /**
     * <code>repeated string movie_names = 1;</code>
     */
    @java.lang.Override
    public java.util.List<java.lang.String> getMovieNamesList() {
      return movieNames_;
    }
    /**
     * <code>repeated string movie_names = 1;</code>
     */
    @java.lang.Override
    public int getMovieNamesCount() {
      return movieNames_.size();
    }
    /**
     * <code>repeated string movie_names = 1;</code>
     */
    @java.lang.Override
    public java.lang.String getMovieNames(int index) {
      return movieNames_.get(index);
    }
    /**
     * <code>repeated string movie_names = 1;</code>
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getMovieNamesBytes(int index) {
      return com.google.protobuf.ByteString.copyFromUtf8(
          movieNames_.get(index));
    }
    private void ensureMovieNamesIsMutable() {
      if (!movieNames_.isModifiable()) {
        movieNames_ =
            com.google.protobuf.GeneratedMessageLite.mutableCopy(movieNames_);
       }
    }
    /**
     * <code>repeated string movie_names = 1;</code>
     */
    private void setMovieNames(
        int index, java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  ensureMovieNamesIsMutable();
      movieNames_.set(index, value);
    }
    /**
     * <code>repeated string movie_names = 1;</code>
     */
    private void addMovieNames(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  ensureMovieNamesIsMutable();
      movieNames_.add(value);
    }
    /**
     * <code>repeated string movie_names = 1;</code>
     */
    private void addAllMovieNames(
        java.lang.Iterable<java.lang.String> values) {
      ensureMovieNamesIsMutable();
      com.google.protobuf.AbstractMessageLite.addAll(
          values, movieNames_);
    }
    /**
     * <code>repeated string movie_names = 1;</code>
     */
    private void clearMovieNames() {
      movieNames_ = com.google.protobuf.GeneratedMessageLite.emptyProtobufList();
    }
    /**
     * <code>repeated string movie_names = 1;</code>
     */
    private void addMovieNamesBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      ensureMovieNamesIsMutable();
      movieNames_.add(value.toStringUtf8());
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      for (int i = 0; i < movieNames_.size(); i++) {
        output.writeString(1, movieNames_.get(i));
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      {
        int dataSize = 0;
        for (int i = 0; i < movieNames_.size(); i++) {
          dataSize += com.google.protobuf.CodedOutputStream
            .computeStringSizeNoTag(movieNames_.get(i));
        }
        size += dataSize;
        size += 1 * getMovieNamesList().size();
      }
      size += unknownFields.getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    public static com.moviematch.MovieMatchProtos.MovieList parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static com.moviematch.MovieMatchProtos.MovieList parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static com.moviematch.MovieMatchProtos.MovieList parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static com.moviematch.MovieMatchProtos.MovieList parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static com.moviematch.MovieMatchProtos.MovieList parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static com.moviematch.MovieMatchProtos.MovieList parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static com.moviematch.MovieMatchProtos.MovieList parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static com.moviematch.MovieMatchProtos.MovieList parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static com.moviematch.MovieMatchProtos.MovieList parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input);
    }
    public static com.moviematch.MovieMatchProtos.MovieList parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static com.moviematch.MovieMatchProtos.MovieList parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static com.moviematch.MovieMatchProtos.MovieList parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }

    public static Builder newBuilder() {
      return (Builder) DEFAULT_INSTANCE.createBuilder();
    }
    public static Builder newBuilder(com.moviematch.MovieMatchProtos.MovieList prototype) {
      return (Builder) DEFAULT_INSTANCE.createBuilder(prototype);
    }

    /**
     * Protobuf type {@code MovieList}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageLite.Builder<
          com.moviematch.MovieMatchProtos.MovieList, Builder> implements
        // @@protoc_insertion_point(builder_implements:MovieList)
        com.moviematch.MovieMatchProtos.MovieListOrBuilder {
      // Construct using com.moviematch.MovieMatchProtos.MovieList.newBuilder()
      private Builder() {
        super(DEFAULT_INSTANCE);
      }


      /**
       * <code>repeated string movie_names = 1;</code>
       */
      @java.lang.Override
      public java.util.List<java.lang.String>
          getMovieNamesList() {
        return java.util.Collections.unmodifiableList(
            instance.getMovieNamesList());
      }
      /**
       * <code>repeated string movie_names = 1;</code>
       */
      @java.lang.Override
      public int getMovieNamesCount() {
        return instance.getMovieNamesCount();
      }
      /**
       * <code>repeated string movie_names = 1;</code>
       */
      @java.lang.Override
      public java.lang.String getMovieNames(int index) {
        return instance.getMovieNames(index);
      }
      /**
       * <code>repeated string movie_names = 1;</code>
       */
      @java.lang.Override
      public com.google.protobuf.ByteString
          getMovieNamesBytes(int index) {
        return instance.getMovieNamesBytes(index);
      }
      /**
       * <code>repeated string movie_names = 1;</code>
       */
      public Builder setMovieNames(
          int index, java.lang.String value) {
        copyOnWrite();
        instance.setMovieNames(index, value);
        return this;
      }
      /**
       * <code>repeated string movie_names = 1;</code>
       */
      public Builder addMovieNames(
          java.lang.String value) {
        copyOnWrite();
        instance.addMovieNames(value);
        return this;
      }
      /**
       * <code>repeated string movie_names = 1;</code>
       */
      public Builder addAllMovieNames(
          java.lang.Iterable<java.lang.String> values) {
        copyOnWrite();
        instance.addAllMovieNames(values);
        return this;
      }
      /**
       * <code>repeated string movie_names = 1;</code>
       */
      public Builder clearMovieNames() {
        copyOnWrite();
        instance.clearMovieNames();
        return this;
      }
      /**
       * <code>repeated string movie_names = 1;</code>
       */
      public Builder addMovieNamesBytes(
          com.google.protobuf.ByteString value) {
        copyOnWrite();
        instance.addMovieNamesBytes(value);
        return this;
      }

      // @@protoc_insertion_point(builder_scope:MovieList)
    }
    @java.lang.Override
    @java.lang.SuppressWarnings({"unchecked", "fallthrough"})
    protected final java.lang.Object dynamicMethod(
        com.google.protobuf.GeneratedMessageLite.MethodToInvoke method,
        java.lang.Object arg0, java.lang.Object arg1) {
      switch (method) {
        case NEW_MUTABLE_INSTANCE: {
          return new com.moviematch.MovieMatchProtos.MovieList();
        }
        case NEW_BUILDER: {
          return new Builder();
        }
        case IS_INITIALIZED: {
          return DEFAULT_INSTANCE;
        }
        case MAKE_IMMUTABLE: {
          movieNames_.makeImmutable();
          return null;
        }
        case VISIT: {
          Visitor visitor = (Visitor) arg0;
          com.moviematch.MovieMatchProtos.MovieList other = (com.moviematch.MovieMatchProtos.MovieList) arg1;
          movieNames_= visitor.visitList(movieNames_, other.movieNames_);
          if (visitor == com.google.protobuf.GeneratedMessageLite.MergeFromVisitor
              .INSTANCE) {
          }
          return this;
        }
        case MERGE_FROM_STREAM: {
          com.google.protobuf.CodedInputStream input =
              (com.google.protobuf.CodedInputStream) arg0;
          com.google.protobuf.ExtensionRegistryLite extensionRegistry =
              (com.google.protobuf.ExtensionRegistryLite) arg1;
          if (extensionRegistry == null) {
            throw new java.lang.NullPointerException();
          }
          try {
            boolean done = false;
            while (!done) {
              int tag = input.readTag();
              switch (tag) {
                case 0:
                  done = true;
                  break;
                case 10: {
                  java.lang.String s = input.readStringRequireUtf8();
                  if (!movieNames_.isModifiable()) {
                    movieNames_ =
                        com.google.protobuf.GeneratedMessageLite.mutableCopy(movieNames_);
                  }
                  movieNames_.add(s);
                  break;
                }
                default: {
                  if (!parseUnknownField(tag, input)) {
                    done = true;
                  }
                  break;
                }
              }
            }
          } catch (com.google.protobuf.InvalidProtocolBufferException e) {
            throw new RuntimeException(e.setUnfinishedMessage(this));
          } catch (java.io.IOException e) {
            throw new RuntimeException(
                new com.google.protobuf.InvalidProtocolBufferException(
                    e.getMessage()).setUnfinishedMessage(this));
          } finally {
          }
        }
        // fall through
        case GET_DEFAULT_INSTANCE: {
          return DEFAULT_INSTANCE;
        }
        case GET_PARSER: {
          com.google.protobuf.Parser<com.moviematch.MovieMatchProtos.MovieList> parser = PARSER;
          if (parser == null) {
            synchronized (com.moviematch.MovieMatchProtos.MovieList.class) {
              parser = PARSER;
              if (parser == null) {
                parser = new DefaultInstanceBasedParser(DEFAULT_INSTANCE);
                PARSER = parser;
              }
            }
          }
          return parser;
      }
      case GET_MEMOIZED_IS_INITIALIZED: {
        return (byte) 1;
      }
      case SET_MEMOIZED_IS_INITIALIZED: {
        return null;
      }
      }
      throw new UnsupportedOperationException();
    }


    // @@protoc_insertion_point(class_scope:MovieList)
    private static final com.moviematch.MovieMatchProtos.MovieList DEFAULT_INSTANCE;
    static {
      // New instances are implicitly immutable so no need to make
      // immutable.
      DEFAULT_INSTANCE = new MovieList();
    }

    public static com.moviematch.MovieMatchProtos.MovieList getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static volatile com.google.protobuf.Parser<MovieList> PARSER;

    public static com.google.protobuf.Parser<MovieList> parser() {
      return DEFAULT_INSTANCE.getParserForType();
    }
  }


  static {
  }

  // @@protoc_insertion_point(outer_class_scope)
}
