// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: movie_opinion.proto

#include "movie_opinion.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/common.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>

class MovieOpinionDefaultTypeInternal {
 public:
  ::google::protobuf::internal::ExplicitlyConstructed<MovieOpinion> _instance;
} _MovieOpinion_default_instance_;
static void InitDefaultsMovieOpinion_movie_5fopinion_2eproto() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  {
    void* ptr = &::_MovieOpinion_default_instance_;
    new (ptr) ::MovieOpinion();
    ::google::protobuf::internal::OnShutdownDestroyMessage(ptr);
  }
  ::MovieOpinion::InitAsDefaultInstance();
}

::google::protobuf::internal::SCCInfo<0> scc_info_MovieOpinion_movie_5fopinion_2eproto =
    {{ATOMIC_VAR_INIT(::google::protobuf::internal::SCCInfoBase::kUninitialized), 0, InitDefaultsMovieOpinion_movie_5fopinion_2eproto}, {}};

void InitDefaults_movie_5fopinion_2eproto() {
  ::google::protobuf::internal::InitSCC(&scc_info_MovieOpinion_movie_5fopinion_2eproto.base);
}

::google::protobuf::Metadata file_level_metadata_movie_5fopinion_2eproto[1];
constexpr ::google::protobuf::EnumDescriptor const** file_level_enum_descriptors_movie_5fopinion_2eproto = nullptr;
constexpr ::google::protobuf::ServiceDescriptor const** file_level_service_descriptors_movie_5fopinion_2eproto = nullptr;

const ::google::protobuf::uint32 TableStruct_movie_5fopinion_2eproto::offsets[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::MovieOpinion, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  PROTOBUF_FIELD_OFFSET(::MovieOpinion, user_id_),
  PROTOBUF_FIELD_OFFSET(::MovieOpinion, movie_name_),
  PROTOBUF_FIELD_OFFSET(::MovieOpinion, thumbs_up_),
};
static const ::google::protobuf::internal::MigrationSchema schemas[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  { 0, -1, sizeof(::MovieOpinion)},
};

static ::google::protobuf::Message const * const file_default_instances[] = {
  reinterpret_cast<const ::google::protobuf::Message*>(&::_MovieOpinion_default_instance_),
};

::google::protobuf::internal::AssignDescriptorsTable assign_descriptors_table_movie_5fopinion_2eproto = {
  {}, AddDescriptors_movie_5fopinion_2eproto, "movie_opinion.proto", schemas,
  file_default_instances, TableStruct_movie_5fopinion_2eproto::offsets,
  file_level_metadata_movie_5fopinion_2eproto, 1, file_level_enum_descriptors_movie_5fopinion_2eproto, file_level_service_descriptors_movie_5fopinion_2eproto,
};

const char descriptor_table_protodef_movie_5fopinion_2eproto[] =
  "\n\023movie_opinion.proto\"F\n\014MovieOpinion\022\017\n"
  "\007user_id\030\001 \001(\004\022\022\n\nmovie_name\030\002 \001(\t\022\021\n\tth"
  "umbs_up\030\003 \001(\010B$\n\016com.moviematchB\022MovieOp"
  "inionProtosb\006proto3"
  ;
::google::protobuf::internal::DescriptorTable descriptor_table_movie_5fopinion_2eproto = {
  false, InitDefaults_movie_5fopinion_2eproto, 
  descriptor_table_protodef_movie_5fopinion_2eproto,
  "movie_opinion.proto", &assign_descriptors_table_movie_5fopinion_2eproto, 139,
};

void AddDescriptors_movie_5fopinion_2eproto() {
  static constexpr ::google::protobuf::internal::InitFunc deps[1] =
  {
  };
 ::google::protobuf::internal::AddDescriptors(&descriptor_table_movie_5fopinion_2eproto, deps, 0);
}

// Force running AddDescriptors() at dynamic initialization time.
static bool dynamic_init_dummy_movie_5fopinion_2eproto = []() { AddDescriptors_movie_5fopinion_2eproto(); return true; }();

// ===================================================================

void MovieOpinion::InitAsDefaultInstance() {
}
class MovieOpinion::HasBitSetters {
 public:
};

#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int MovieOpinion::kUserIdFieldNumber;
const int MovieOpinion::kMovieNameFieldNumber;
const int MovieOpinion::kThumbsUpFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

MovieOpinion::MovieOpinion()
  : ::google::protobuf::Message(), _internal_metadata_(nullptr) {
  SharedCtor();
  // @@protoc_insertion_point(constructor:MovieOpinion)
}
MovieOpinion::MovieOpinion(const MovieOpinion& from)
  : ::google::protobuf::Message(),
      _internal_metadata_(nullptr) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  movie_name_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  if (from.movie_name().size() > 0) {
    movie_name_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.movie_name_);
  }
  ::memcpy(&user_id_, &from.user_id_,
    static_cast<size_t>(reinterpret_cast<char*>(&thumbs_up_) -
    reinterpret_cast<char*>(&user_id_)) + sizeof(thumbs_up_));
  // @@protoc_insertion_point(copy_constructor:MovieOpinion)
}

void MovieOpinion::SharedCtor() {
  ::google::protobuf::internal::InitSCC(
      &scc_info_MovieOpinion_movie_5fopinion_2eproto.base);
  movie_name_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  ::memset(&user_id_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&thumbs_up_) -
      reinterpret_cast<char*>(&user_id_)) + sizeof(thumbs_up_));
}

MovieOpinion::~MovieOpinion() {
  // @@protoc_insertion_point(destructor:MovieOpinion)
  SharedDtor();
}

void MovieOpinion::SharedDtor() {
  movie_name_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}

void MovieOpinion::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}
const MovieOpinion& MovieOpinion::default_instance() {
  ::google::protobuf::internal::InitSCC(&::scc_info_MovieOpinion_movie_5fopinion_2eproto.base);
  return *internal_default_instance();
}


void MovieOpinion::Clear() {
// @@protoc_insertion_point(message_clear_start:MovieOpinion)
  ::google::protobuf::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  movie_name_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  ::memset(&user_id_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&thumbs_up_) -
      reinterpret_cast<char*>(&user_id_)) + sizeof(thumbs_up_));
  _internal_metadata_.Clear();
}

#if GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
const char* MovieOpinion::_InternalParse(const char* begin, const char* end, void* object,
                  ::google::protobuf::internal::ParseContext* ctx) {
  auto msg = static_cast<MovieOpinion*>(object);
  ::google::protobuf::int32 size; (void)size;
  int depth; (void)depth;
  ::google::protobuf::uint32 tag;
  ::google::protobuf::internal::ParseFunc parser_till_end; (void)parser_till_end;
  auto ptr = begin;
  while (ptr < end) {
    ptr = ::google::protobuf::io::Parse32(ptr, &tag);
    GOOGLE_PROTOBUF_PARSER_ASSERT(ptr);
    switch (tag >> 3) {
      // uint64 user_id = 1;
      case 1: {
        if (static_cast<::google::protobuf::uint8>(tag) != 8) goto handle_unusual;
        msg->set_user_id(::google::protobuf::internal::ReadVarint(&ptr));
        GOOGLE_PROTOBUF_PARSER_ASSERT(ptr);
        break;
      }
      // string movie_name = 2;
      case 2: {
        if (static_cast<::google::protobuf::uint8>(tag) != 18) goto handle_unusual;
        ptr = ::google::protobuf::io::ReadSize(ptr, &size);
        GOOGLE_PROTOBUF_PARSER_ASSERT(ptr);
        ctx->extra_parse_data().SetFieldName("MovieOpinion.movie_name");
        object = msg->mutable_movie_name();
        if (size > end - ptr + ::google::protobuf::internal::ParseContext::kSlopBytes) {
          parser_till_end = ::google::protobuf::internal::GreedyStringParserUTF8;
          goto string_till_end;
        }
        GOOGLE_PROTOBUF_PARSER_ASSERT(::google::protobuf::internal::StringCheckUTF8(ptr, size, ctx));
        ::google::protobuf::internal::InlineGreedyStringParser(object, ptr, size, ctx);
        ptr += size;
        break;
      }
      // bool thumbs_up = 3;
      case 3: {
        if (static_cast<::google::protobuf::uint8>(tag) != 24) goto handle_unusual;
        msg->set_thumbs_up(::google::protobuf::internal::ReadVarint(&ptr));
        GOOGLE_PROTOBUF_PARSER_ASSERT(ptr);
        break;
      }
      default: {
      handle_unusual:
        if ((tag & 7) == 4 || tag == 0) {
          ctx->EndGroup(tag);
          return ptr;
        }
        auto res = UnknownFieldParse(tag, {_InternalParse, msg},
          ptr, end, msg->_internal_metadata_.mutable_unknown_fields(), ctx);
        ptr = res.first;
        GOOGLE_PROTOBUF_PARSER_ASSERT(ptr != nullptr);
        if (res.second) return ptr;
      }
    }  // switch
  }  // while
  return ptr;
string_till_end:
  static_cast<::std::string*>(object)->clear();
  static_cast<::std::string*>(object)->reserve(size);
  goto len_delim_till_end;
len_delim_till_end:
  return ctx->StoreAndTailCall(ptr, end, {_InternalParse, msg},
                               {parser_till_end, object}, size);
}
#else  // GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
bool MovieOpinion::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!PROTOBUF_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:MovieOpinion)
  for (;;) {
    ::std::pair<::google::protobuf::uint32, bool> p = input->ReadTagWithCutoffNoLastTag(127u);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // uint64 user_id = 1;
      case 1: {
        if (static_cast< ::google::protobuf::uint8>(tag) == (8 & 0xFF)) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::uint64, ::google::protobuf::internal::WireFormatLite::TYPE_UINT64>(
                 input, &user_id_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // string movie_name = 2;
      case 2: {
        if (static_cast< ::google::protobuf::uint8>(tag) == (18 & 0xFF)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_movie_name()));
          DO_(::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
            this->movie_name().data(), static_cast<int>(this->movie_name().length()),
            ::google::protobuf::internal::WireFormatLite::PARSE,
            "MovieOpinion.movie_name"));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // bool thumbs_up = 3;
      case 3: {
        if (static_cast< ::google::protobuf::uint8>(tag) == (24 & 0xFF)) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   bool, ::google::protobuf::internal::WireFormatLite::TYPE_BOOL>(
                 input, &thumbs_up_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, _internal_metadata_.mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:MovieOpinion)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:MovieOpinion)
  return false;
#undef DO_
}
#endif  // GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER

void MovieOpinion::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:MovieOpinion)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // uint64 user_id = 1;
  if (this->user_id() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteUInt64(1, this->user_id(), output);
  }

  // string movie_name = 2;
  if (this->movie_name().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->movie_name().data(), static_cast<int>(this->movie_name().length()),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "MovieOpinion.movie_name");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      2, this->movie_name(), output);
  }

  // bool thumbs_up = 3;
  if (this->thumbs_up() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteBool(3, this->thumbs_up(), output);
  }

  if (_internal_metadata_.have_unknown_fields()) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        _internal_metadata_.unknown_fields(), output);
  }
  // @@protoc_insertion_point(serialize_end:MovieOpinion)
}

::google::protobuf::uint8* MovieOpinion::InternalSerializeWithCachedSizesToArray(
    ::google::protobuf::uint8* target) const {
  // @@protoc_insertion_point(serialize_to_array_start:MovieOpinion)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // uint64 user_id = 1;
  if (this->user_id() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteUInt64ToArray(1, this->user_id(), target);
  }

  // string movie_name = 2;
  if (this->movie_name().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->movie_name().data(), static_cast<int>(this->movie_name().length()),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "MovieOpinion.movie_name");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        2, this->movie_name(), target);
  }

  // bool thumbs_up = 3;
  if (this->thumbs_up() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteBoolToArray(3, this->thumbs_up(), target);
  }

  if (_internal_metadata_.have_unknown_fields()) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields(), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:MovieOpinion)
  return target;
}

size_t MovieOpinion::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:MovieOpinion)
  size_t total_size = 0;

  if (_internal_metadata_.have_unknown_fields()) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        _internal_metadata_.unknown_fields());
  }
  ::google::protobuf::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // string movie_name = 2;
  if (this->movie_name().size() > 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::StringSize(
        this->movie_name());
  }

  // uint64 user_id = 1;
  if (this->user_id() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::UInt64Size(
        this->user_id());
  }

  // bool thumbs_up = 3;
  if (this->thumbs_up() != 0) {
    total_size += 1 + 1;
  }

  int cached_size = ::google::protobuf::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void MovieOpinion::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:MovieOpinion)
  GOOGLE_DCHECK_NE(&from, this);
  const MovieOpinion* source =
      ::google::protobuf::DynamicCastToGenerated<MovieOpinion>(
          &from);
  if (source == nullptr) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:MovieOpinion)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:MovieOpinion)
    MergeFrom(*source);
  }
}

void MovieOpinion::MergeFrom(const MovieOpinion& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:MovieOpinion)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  if (from.movie_name().size() > 0) {

    movie_name_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.movie_name_);
  }
  if (from.user_id() != 0) {
    set_user_id(from.user_id());
  }
  if (from.thumbs_up() != 0) {
    set_thumbs_up(from.thumbs_up());
  }
}

void MovieOpinion::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:MovieOpinion)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void MovieOpinion::CopyFrom(const MovieOpinion& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:MovieOpinion)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool MovieOpinion::IsInitialized() const {
  return true;
}

void MovieOpinion::Swap(MovieOpinion* other) {
  if (other == this) return;
  InternalSwap(other);
}
void MovieOpinion::InternalSwap(MovieOpinion* other) {
  using std::swap;
  _internal_metadata_.Swap(&other->_internal_metadata_);
  movie_name_.Swap(&other->movie_name_, &::google::protobuf::internal::GetEmptyStringAlreadyInited(),
    GetArenaNoVirtual());
  swap(user_id_, other->user_id_);
  swap(thumbs_up_, other->thumbs_up_);
}

::google::protobuf::Metadata MovieOpinion::GetMetadata() const {
  ::google::protobuf::internal::AssignDescriptors(&::assign_descriptors_table_movie_5fopinion_2eproto);
  return ::file_level_metadata_movie_5fopinion_2eproto[kIndexInFileMessages];
}


// @@protoc_insertion_point(namespace_scope)
namespace google {
namespace protobuf {
template<> PROTOBUF_NOINLINE ::MovieOpinion* Arena::CreateMaybeMessage< ::MovieOpinion >(Arena* arena) {
  return Arena::CreateInternal< ::MovieOpinion >(arena);
}
}  // namespace protobuf
}  // namespace google

// @@protoc_insertion_point(global_scope)
#include <google/protobuf/port_undef.inc>
